sonar.projectKey=notely
sonar.projectName=Notely
sonar.sourceEncoding=UTF-8
sonar.sources=client/src,server,shared,drizzle
sonar.tests=server
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx
sonar.exclusions=**/node_modules/**,**/dist/**,**/drizzle/migrations/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
